#!/usr/bin/env python3
"""
stub_from_gap.py
Scaffold a language-correct stub + minimal tests from a backlog CSV row (by ID).
"""
import argparse, csv, os, re, shutil
from pathlib import Path

def slug(s: str) -> str:
    s = s.lower()
    s = re.sub(r'[^a-z0-9]+','-', s).strip('-')
    return s or "item"

def read_row(csv_path: Path, gap_id: str):
    with csv_path.open("r", encoding="utf-8") as f:
        r = csv.DictReader(f)
        for row in r:
            rid = (row.get("ID") or "").strip()
            if rid == gap_id:
                return row
    raise SystemExit(f"ID {gap_id} not found in {csv_path}")

def write(p: Path, content: str):
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")

def gen_python(dst: Path):
    write(dst/"stub.py", """from typing import Any, Dict

def run(input: Dict[str, Any]) -> Dict[str, Any]:
    # TODO: implement
    return {"ok": True, "echo": input}
""")
    write(dst/"tests/test_stub.py", """from importlib import import_module

def test_run_minimal():
    m = import_module(__name__.replace('.tests.test_stub','') + '.stub')
    out = m.run({"x": 1})
    assert out["ok"] is True
""")

def gen_typescript(dst: Path):
    write(dst/"stub.ts", """export type Input = Record<string, unknown>;
export type Output = { ok: boolean; echo: Input };

export function run(input: Input): Output {
  // TODO: implement
  return { ok: true, echo: input };
}
""")
    write(dst/"tests/test_stub.ts", """import { strict as assert } from 'node:assert';
import { run } from '../stub';

describe('stub.ts', () => {
  it('minimal', () => {
    const out = run({x:1});
    assert.equal(out.ok, true);
  });
});
""")

def gen_rust(dst: Path, crate_name: str):
    write(dst/"Cargo.toml", f"""[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
""")
    write(dst/"src/lib.rs", """use serde_json::{Value, json};

pub fn run(_input: &Value) -> Value {
    json!({ "ok": true })
}
""")

def gen_c(dst: Path):
    write(dst/"src/main.c", r"""#include <stdio.h>
int main(void) {
  // TODO: parse stdin JSON if needed
  printf("{"ok":true}
");
  return 0;
}
""")
    write(dst/"README.md", "# C stub

Build with your preferred toolchain.
")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", required=True, help="Backlog CSV path")
    ap.add_argument("--id", required=True, help="ID (e.g., K1001 / S721)")
    ap.add_argument("--root", default=".", help="Repo root (where stubs/ lives)")
    ap.add_argument("--stub-root", default="stubs/gaps", help="Where to place new stubs")
    ap.add_argument("--lang-override", choices=["python","typescript","rust","c"], help="Force language")
    args = ap.parse_args()

    csv_path = Path(args.csv)
    row = read_row(csv_path, args.id)

    title = row.get("Title","").strip() or args.id
    lang = (args.lang_override or (row.get("Language","") or "python").lower()).strip()
    path = (row.get("Path","").strip())
    if not path:
        path = f"{args.stub_root}/{args.id}-{slug(title)}"

    dst = Path(args.root) / path
    print(f"Scaffolding -> {dst} (language={lang})")

    if lang == "python":
        gen_python(dst)
    elif lang in ("ts","typescript"):
        gen_typescript(dst)
    elif lang == "rust":
        crate_name = slug(Path(path).name)
        gen_rust(dst, crate_name)
    elif lang == "c":
        gen_c(dst)
    else:
        print(f"Unknown language '{lang}', defaulting to python.")
        gen_python(dst)

    # generic README
    write(dst/"README.md", f"# {args.id} – {title}\n\nLanguage: {lang}\n\nAuto-generated by stub_from_gap.py\n")

    print("Done.")

if __name__ == "__main__":
    main()
